### ISSUE TITLE
API is at version 2.0

### ISSUE THREAD

**Issue by mhajda** [NathanielWroblewski/weather_widget#1]
Thanks for putting this together.  Upon first attempt the API call was failing, and after troubleshooting with weather site's API, it looks like they are now on V2 and deprecating the V1 calls.  

Line 10 needs to be updated from:
       'http://api.worldweatheronline.com/free/v1/weather.ashx' +
to:
       'http://api.worldweatheronline.com/free/v2/weather.ashx' +

**Comment by NathanielWroblewski** [comment]
Thanks for bringing this to my attention.  This is fixed with [d6e68e](https://github.com/NathanielWroblewski/weather_widget/commit/d6e68e6d669abd3c9e175bfd7c420f8fcd6f7b2e).
